name: Test scripting

on:
  pull_request:
    paths-ignore:
      - 'screenshots/**'
      
jobs:
  screenshot:
    if: ${{ github.event.head_commit.message != 'Bot Updated screenshots' }}
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{ github.event.head_commit.message }}
      - name: Prepare Git
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          token: ${{ secrets.GH_ACCESS_TOKEN }}
      - name: Do stuff
        run: |
          date > text.txt
      # - name: Commit Changes
      #   env:
      #       BRANCH_BASE: ${{ github.head_ref }}
      #   run: |
      #     GIT_STATUS=$(git status --porcelain)
      #     if [[ -n "$GIT_STATUS" ]]
      #     then
      #       git config --global user.email "bot@action.bot"
      #       git config --global user.name "beep-boop"
      #       git add .
      #       git commit -m "Bot Updated screenshots"
      #       git push origin $BRANCH_BASE
      #     fi