name: Test scripting

on:
  pull_request:
    paths-ignore:
      - 'screenshots/**'
      
jobs:
  screenshot:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Prepare Git
        env:
            BRANCH_BASE: ${{ github.head_ref }}
        run: |
          echo Base branch is $BRANCH_BASE
          git fetch origin
          git checkout -b $BRANCH_BASE origin/$BRANCH_BASE
      - name: Do stuff
        run: |
          date > text.txt
      - name: Do stuff
        env:
            BRANCH_BASE: ${{ github.head_ref }}
        run: |
          if [[ -z $(git status --porcelain) ]] 
          then
            git add .
            git commit -m "Addde CI"
            git push origin $BRANCH_BASE
          fi
