name: Test scripting

on:
  push:
    tags:
      - '*'
      
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - MY_BUILD_TYPE: TYPE_123
          - MY_BUILD_TYPE: TYPE_ABC
          - MY_BUILD_TYPE: TYPE_XYZ
          
    steps:
      - name: Check Tag
        env:
          GH_TAG: ${{ github.ref }}
        run: ./check_tag.sh "${GH_TAG}"
      - name: Next step
        if: ${{ contains(steps.check-tag.outputs.TAG_BUILD_TYPES, matrix.MY_BUILD_TYPE) }}
        run: echo I'm running !!
      - name: Last step
        if: ${{ contains(steps.check-tag.outputs.TAG_BUILD_TYPES, matrix.MY_BUILD_TYPE) }}
        run: echo I'm running faster!
