name: Test scripting

on:
  push:
    tags:
      - '*'
      
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - MY_BUILD_TYPE: TYPE_123
          - MY_BUILD_TYPE: TYPE_ABC
          - MY_BUILD_TYPE: TYPE_XYZ
          
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
      - name: Check Tag
        id: check-tag
        env:
          GH_TAG: ${{ github.ref }}
        run: |
          chmod +x check_tag.sh
          ./check_tag.sh "${GH_TAG}"
      - name: printf
        env:
          GH_TAG: ${{ github.ref }}
          MY_BUILD_TYPE: ${{ matrix.MY_BUILD_TYPE }}
          TAG_TYPE: ${{ steps.check-tag.outputs.TAG_BUILD_TYPES }}
        run: |
          echo "GH_TAG = $GH_TAG"
          echo "MY_BUILD_TYPE = $MY_BUILD_TYPE"
          echo "TAG_TYPE = $TAG_TYPE"
      - name: Next step
        if: ${{ contains(steps.check-tag.outputs.TAG_BUILD_TYPES, matrix.MY_BUILD_TYPE) }}
        run: echo "I'm running !!"
      - name: Last step
        if: ${{ contains(steps.check-tag.outputs.TAG_BUILD_TYPES, matrix.MY_BUILD_TYPE) }}
        run: echo "I'm running faster!"
