name: Test scripting

on:
  push:
    tags:
      - '*'
      
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - MY_BUILD_TYPE: TYPE_123
          - MY_BUILD_TYPE: TYPE_ABC
          - MY_BUILD_TYPE: TYPE_XYZ
          
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
      - name: Check Tag
        id: check-tag
        env:
          GH_TAG: ${{ github.ref }}
          MY_BUILD_TYPE: ${{ matrix.MY_BUILD_TYPE }}
        run: |
          chmod +x check_tag.sh
          ./check_tag.sh "${GH_TAG}" "${MY_BUILD_TYPE}"
      - name: See result from check tag
        env:
          CONTINUE: ${{ steps.check-tag.outputs.CONTINUE }}      
        run: echo "Should I stay or should I go ${CONTINUE}"
      - name: Next step
        if: ${{ steps.check-tag.outputs.CONTINUE == 'true' }}
        run: echo "I'm running !!"
      - name: Last step
        if: ${{ steps.check-tag.outputs.CONTINUE == 'true' }}
        run: echo "I'm running faster!"
